task 1 lesson 1
MCaberGIT/invoicing-system-michal-caber pull request #1
Opened 2022-10-17 18:50 UTC by MCaberGIT

2022-10-20 09:52 UTC, patryk-stepniak requested changes
O wiele lepiej :)
Brakuje jednak konfiguracji checkstylera w build.gradle:
checkstyle {
    showViolations = true
    ignoreFailures = false
    maxWarnings = 0
    maxErrors = 0
}

2022-10-25 06:56 UTC, patryk-stepniak approved these changes

2022-10-25 06:56 UTC, patryk-stepniak approved these changes, later dismissed

2022-10-28 16:20 UTC, BartoszKamyszek approved these changes

2022-10-28 16:24 UTC, merged