lesson2 task 1
MCaberGIT/invoicing-system-michal-caber pull request #2
Opened 2022-10-31 16:07 UTC by MCaberGIT

2022-11-01 11:30 UTC, patryk-stepniak requested changes
Brakuje implementacji service'u, testów oraz przydało by się jakieś przykładowe użycie kodu.

2022-11-01 11:30 UTC, patryk-stepniak commented on app/src/main/java/pl/futurecollars/invoicing/service/InvoiceService.java
> +}
Trochę tu pusto

2022-11-01 11:31 UTC, patryk-stepniak commented
Nie widzę również konfiguracji githubowego pipeline'a.

2022-11-10 17:16 UTC, BartoszKamyszek approved these changes

2022-11-10 17:26 UTC, merged